### ISSUE TITLE
Let's explore the data

### ISSUE THREAD

**Issue by docligot** [apolbernardo/paper_1#4]
Let's create a data exploration report. 

In the /data folder, create a new readme.md (no .txt) file and describe: 

* Dataset source
* Original purpose
* Data columns

Determine, the target variable (mental_health?). On another file (excel/PBI/python notebook), perform a data visualization crossing the target variable with each of the other variables. 

Save this file in the /data folder

**Comment by docligot** [comment]
Created a branch called "eda-folder" with a sample visualization and pivot table. You can use this as a peg for the EDA. 

Fetch the changes on Github for Windows and you should see the branch.

**Comment by apolbernardo** [comment]
I need help in chi square independency(first time) I run that stat treatment since I want to know if there is relationship between employees who has HMO benefit vs employees with MH package benefits and since categorical yes or no. but Im confused when the graph at my ntbk can you explain the graph thanks this is my ntbk link https://colab.research.google.com/drive/1lo0Zukz81vzVqbo77willYR4FuFPof2i#scrollTo=X-ch_AEb_YVx  under this header HMO coverage vs Mental health package

**Comment by docligot** [comment]
The graph just shows the relative number of yes/no for mental health benefits per category of mental health yes/no

Since the chi-square is significant (i.e. p-value <0.05) it means that the variable of mental health yes/no influences the ratio of mental health benefits yes/no

You can convert the data into percentages to see this better.

**Comment by apolbernardo** [comment]
it stated that there is association between employees who has HMO and with MH package and i was expecting in the graph it will reflect that if HMO if high same to HM package but thats not what the graph reflects which is the other way around when HMO is high MH is low that made me confuse.

**Comment by docligot** [comment]
No what association means is the 1st variable affects the 2nd variable - so it's ok that the 2 graphs are different. 

As to the direction of the relationship - that's where the insight should be.
